var cp;cp||(cp={});cp.charts={};cp.charts.isReady=function(){return cp.charts.ready};cp.charts.userCallback=null;
cp.charts.init=function(a){cp.charts.ready=!1;cp.charts.colors="#cc3754 #208fd8 #d9672a #d385bc #465235 #4c6e1e #807d61 #bd73c5 #a3653a #dacf33 #66216e #1e344f #4b35cd #5fcb5f #c8d96a #48b15d #70dbb8 #ab8c3d #839c93 #bf4628 #7133c7 #6f9f84 #5029c1 #8760c0 #326986 #978f47 #945fd4 #8a714a #82da38 #68cdd6 #59dbb1 #43b8d7 #81a05d #d87670 #228ec1 #c7ad82 #7ad8b2 #517541 #6dada2 #5b9087 #592850 #363ece #457fa5 #44d834 #7f9895 #4facc8 #509725 #7b7297 #71a85f #866e46 #39c3c3 #8b6eac #d56f84 #d8c379 #92abd1 #345c40 #58a078 #25c9db #9e457a #b66530 #c888a2 #3bd83d #57457c #719ebb #745643 #657c40 #ab1f43 #1eac5b #c74422 #cba12f #d2a2d0 #75cda4 #407b7c #d19eb3 #3d7448 #8fa686 #2dc231 #205740 #7969b5 #43685a #6e9c9b #96696e #6e986f #acd44f #703a73 #755323 #292c3d #4fb594 #5c58d4 #6baea5 #9439a7 #33be2c #d77e97 #c18732 #a62475 #3ec58d #25a28c #564028 #328052 #788023".split(" ");void 0!=
a&&(cp.charts.userCallback=a);cp.loadScript("https://www.google.com/jsapi?autoload={'modules':[{'name':'visualization','version':'1','packages':['corechart'],'callback':'cp.charts.initCallback'}]}")};cp.charts.initCallback=function(){cp.charts.ready=!0;cp.log("cp.charts: version 2013-09-22");null!=cp.charts.userCallback&&void 0!=cp.charts.userCallback&&cp.charts.userCallback()};
cp.charts.retrievePopData=function(a,b,d){a=$.ajax({url:"retrieveChartData.php?pageid="+a+"&type="+b+"&id="+d,dataType:"json",async:!1}).responseText;a=$.parseJSON(a);return""!=a.error?(cp.log("retrievePopData: "+a.error),null):a};
cp.charts.extractPopData=function(a,b){for(var d=-1,h=0;h<a.getNumberOfRows();h++)if(a.getID(h)==b){d=h;break}if(!(0>d)){var g={};g.name=a.getName(d);g.admname=null;g.status="";g.popNum=a.getNumberOfPopColumns();g.pop=[];g.years=[];for(h=0;h<g.popNum;h++)g.pop.push(a.getValue(d,a.getPopColumnIndex(h))),g.years.push(a.getColumnProperty(a.getPopColumnIndex(h),cp.charts.COLDATE_PROP));return g}};cp.charts.CHART_SIZE_SMALL="small";cp.charts.CHART_SIZE_LARGE="large";
cp.charts.isPopDevDialogOcHandlerSet=!1;
cp.charts.showPopDevDialog=function(a){if(null!=a){var b;b='<iframe id="cp_chart_popdev_adv" src="/php/diagradv.html" scrolling="no"></iframe>';cp.getVizMode()!=cp.VIZMODE_DESKTOP&&(b+='<img id="cp_chart_popdev_close" src="/images/close.gif" alt="close" onclick="cp.charts.closePopDevDialog()">');b+="<h1>"+a.name+"</h1>";b+="<h2>"+a.status;null!=a.admname&&(b+=" in "+a.admname);b+='</h2><div id="cp_chart_popdev_chart"></div>';b+="<p>&copy; http://www.citypopulation.de, 2013</p>";if(0==$("#cp_chart_popdev_div").length){var d=
document.createElement("div");d.id="cp_chart_popdev_div";d.className="ui-corner-all ui-widget ui-widget-content";document.getElementsByTagName("body")[0].appendChild(d)}$("#cp_chart_popdev_div").html(b);var h=[];for(b=0;b<a.years.length;b++)"string"==typeof a.years[b]?h.push(cp.data.toDate(a.years[b])):h.push(a.years[b]);cp.getVizMode()==cp.VIZMODE_DESKTOP?(cp.charts.drawPopDevChart(cp.charts.CHART_SIZE_LARGE,document.getElementById("cp_chart_popdev_chart"),h,a.pop),$("#cp_chart_popdev_div").is(":data(dialog)")?
$("#cp_chart_popdev_div").dialog("open"):$("#cp_chart_popdev_div").dialog({width:"auto",height:"auto",resizable:!1,title:cp.getLangText("Einwohnerentwicklung","Population Development")})):(cp.charts.isPopDevDialogOcHandlerSet||(cp.addOcCallback(function(){cp.charts.definePopDevDialogCSS(h,a.pop)}),cp.charts.isPopDevDialogOcHandlerSet=!0),cp.charts.definePopDevDialogCSS(h,a.pop));$("#cp_chart_popdev_div").css("visibility","visible")}};
cp.charts.definePopDevDialogCSS=function(a,b){var d=window.pageYOffset;cp.getVizMode()==cp.VIZMODE_MOBIPORTRAIT?($("#cp_chart_popdev_div").css("top",d+70+"px"),$("#cp_chart_popdev_div").css("left","0px")):($("#cp_chart_popdev_div").css("top",d+"px"),$("#cp_chart_popdev_div").css("left","70px"));cp.charts.drawPopDevChart(cp.charts.CHART_SIZE_LARGE,document.getElementById("cp_chart_popdev_chart"),a,b)};cp.charts.closePopDevDialog=function(){$("#cp_chart_popdev_div").css("visibility","hidden")};
cp.charts.drawPopDevChart=function(a,b,d,h){try{if(!cp.charts.ready||null==b||null==h)return null;var g=cp.getLangText("Einwohner","Population"),k=new google.visualization.DataTable;k.addColumn({type:"date",label:cp.getLangText("Datum","Date"),pattern:"yyyy-MM-dd"});k.addColumn("number",g);for(g=0;g<d.length;g++)0<h[g]?k.addRow([d[g],h[g]]):k.addRow([d[g],null]),0<h[g]&&(mapPop=h[g]);var e={legend:{position:"none"},vAxis:{minValue:0},colors:[cp.charts.colors[0]],backgroundColor:{stroke:"#aaa",strokeWidth:2},
chartArea:{}};a==cp.charts.CHART_SIZE_SMALL?(e.width=170,e.height=100,e.pointSize=4,e.chartArea.left=50,e.chartArea.width=110):cp.getVizMode()==cp.VIZMODE_DESKTOP?(e.width=468,e.height=300,e.pointSize=8,e.chartArea.left=90,e.chartArea.width=350,e.chartArea.top=40,e.chartArea.height=220):cp.getVizMode()==cp.VIZMODE_MOBIPORTRAIT?(e.width=310,e.height=220,e.pointSize=6,e.chartArea.left=70,e.chartArea.width=225,e.chartArea.top=15,e.chartArea.height=180):(e.width=330,e.height=190,e.pointSize=6,e.chartArea.left=
80,e.chartArea.width=225,e.chartArea.top=15,e.chartArea.height=160);var f=new google.visualization.LineChart(b);f.draw(k,e);return f}catch(c){return cp.log("drawPopDevChart: "+c),null}};cp.charts.ID_COL=0;cp.charts.NAME_COL=1;cp.charts.OTHERNAME_COL=2;cp.charts.ABBR_COL=3;cp.charts.ADM_COL=4;cp.charts.STATUS_COL=5;cp.charts.CAPITAL_COL=6;cp.charts.OTHER_COL=7;cp.charts.AREA_COL=8;cp.charts.POP_COL=9;cp.charts.VALUE_COL=cp.charts.POP_COL;cp.charts.DIVVAL_COL=10;cp.charts.RANK_COL=11;
cp.charts.AGGLO_COL=12;cp.charts.COLTYPE_PROP="COLTYPE";cp.charts.COLDATE_PROP="COLDATE";cp.charts.COLUNIT_PROP="COLUNIT";
cp.charts.computeColType=function(a){a=a.trim();if("Name"==a||"English Name"==a||"Deutscher Name"==a||"Country"==a)return cp.charts.NAME_COL;if("Original"==a||"Native"==a)return cp.charts.OTHERNAME_COL;if("Abbr."==a||"Abk."==a)return cp.charts.ABBR_COL;if("Adm."==a||"Staat"==a||"Country"==a)return cp.charts.ADM_COL;if("Status"==a)return cp.charts.STATUS_COL;if("Capital"==a||"Hauptstadt"==a)return cp.charts.CAPITAL_COL;if("&nbsp;"==a||"Remark"==a||"Bemerkung"==a||"Date"==a)return cp.charts.OTHER_COL;
a=a.substr(0,3);return"A ("==a||"A-L"==a||"C A"==a?cp.charts.AREA_COL:cp.charts.POP_COL};
cp.charts.evalColType=function(a){return"name"==a?cp.charts.NAME_COL:"othername"==a?cp.charts.OTHERNAME_COL:"id"==a?cp.charts.ID_COL:"abbr"==a?cp.charts.ABBR_COL:"adm"==a?cp.charts.ADM_COL:"status"==a?cp.charts.STATUS_COL:"capital"==a?cp.charts.CAPITAL_COL:"area"==a?cp.charts.AREA_COL:"pop"==a||"val"==a?cp.charts.POP_COL:"divval"==a?cp.charts.DIVVAL_COL:"rank"==a?cp.charts.RANK_COL:"agglo"==a?cp.charts.AGGLO_COL:cp.charts.OTHER_COL};
cp.charts.DataContainer=function(a,b,d,h){a=document.getElementById(a);if(null!=a){b=a.rows.length-b;var g=a.rows[0].cells.length,k=Array(g),e=new google.visualization.DataTable;this.popCols=[];this.admCol=-1;this.nameCol=1;this.areaCol=-1;for(var f=0;f<g;f++){var c=a.rows[0].cells[f],j=cp.charts.computeColType(c.textContent);if("noviz"==c.className||"empty"==c.className)j=cp.charts.OTHER_COL;var l=c.getAttribute("data-coltype");void 0!=l&&(j=cp.charts.evalColType(l));j==cp.charts.ADM_COL&&(this.admCol=
f);j==cp.charts.NAME_COL&&(this.nameCol=f);j==cp.charts.AREA_COL&&(this.areaCol=f);k[f]=j==cp.charts.AREA_COL||j==cp.charts.POP_COL||j==cp.charts.DIVVAL_COL;l=c.getAttribute("data-colhead");l=void 0==l?c.textContent:l;k[f]?e.addColumn("number",l):e.addColumn("string",l);e.setColumnProperty(f,cp.charts.COLTYPE_PROP,j);void 0!=c.getAttribute("data-colunit")&&e.setColumnProperty(f,cp.charts.COLUNIT_PROP,c.getAttribute("data-colunit"));if(j==cp.charts.POP_COL||j==cp.charts.DIVVAL_COL)c=c.getAttribute("data-coldate"),
c=cp.data.toDate(void 0==c?l:c),e.setColumnProperty(f,cp.charts.COLDATE_PROP,c),this.popCols.push(f)}e.addColumn("string","id");this.idCol=g;e.setColumnProperty(g,cp.charts.COLTYPE_PROP,cp.charts.ID_COL);for(d=void 0==d?1:d;d<b;d++){c=a.rows[d].cells[0].id;if((void 0==c||""==c)&&void 0!=a.rows[d].cells[1])c=a.rows[d].cells[1].id;a.rows[d].cells[this.nameCol]&&("provt"==a.rows[d].cells[this.nameCol].className&&!0!=h)&&(c=null);if(null!=c&&void 0!=c&&""!=c){j=[];l=cp.data.cValue(a.rows[d].cells[this.nameCol],
!1);0<=this.admCol&&""!=cp.data.cValue(a.rows[d].cells[this.admCol],!1).trim()&&(l+=" ["+cp.data.cValue(a.rows[d].cells[this.admCol],!1)+"]");for(f=0;f<g;f++)if(f!=this.nameCol){var p=!1;a.rows[d].cells[f].firstElementChild&&(p="a"==a.rows[d].cells[f].firstElementChild.getAttribute("data-status"));j.push(p?void 0:cp.data.cValue(a.rows[d].cells[f],k[f]))}else j.push(l);j.push(c.substr(1));e.addRow(j)}}this.data=e}};cp.charts.DataContainer.prototype.getData=function(){return this.data};
cp.charts.DataContainer.prototype.getNumberOfColumns=function(){return this.data.getNumberOfColumns()};cp.charts.DataContainer.prototype.getColumnLabel=function(a){return this.data.getColumnLabel(a)};cp.charts.DataContainer.prototype.getColumnProperty=function(a,b){return this.data.getColumnProperty(a,b)};cp.charts.DataContainer.prototype.getNumberOfPopColumns=function(){return this.popCols.length};cp.charts.DataContainer.prototype.getPopColumnIndex=function(a){return 0>a?-1:this.popCols[a]};
cp.charts.DataContainer.prototype.getNumberOfValueColumns=function(){return this.popCols.length};cp.charts.DataContainer.prototype.getValueColumnIndex=function(a){return this.popCols[a]};cp.charts.DataContainer.prototype.getAdmColumnIndex=function(){return this.admCol};cp.charts.DataContainer.prototype.getAreaColumnIndex=function(){return this.areaCol};cp.charts.DataContainer.prototype.getNumberOfRows=function(){return this.data.getNumberOfRows()};
cp.charts.DataContainer.prototype.getValue=function(a,b){return this.data.getValue(a,b)};cp.charts.DataContainer.prototype.getID=function(a){return this.data.getValue(a,this.idCol)};cp.charts.DataContainer.prototype.getAllIDs=function(){for(var a=[],b=0;b<this.data.getNumberOfRows();b++)a.push(this.data.getValue(b,this.idCol));return a};cp.charts.DataContainer.prototype.getName=function(a){return this.data.getValue(a,this.nameCol)};
cp.charts.DataContainer.prototype.getRowIndexByID=function(a){for(var b=0;b<this.data.getNumberOfRows();b++)if(this.data.getValue(b,this.idCol)==a)return b;return-1};cp.charts.DataContainer.prototype.sortByName=function(){var a=[{column:this.nameCol}];0<=this.admCol&&a.push({column:this.admCol});this.data.sort(a)};cp.charts.DataContainer.prototype.sortByAdmin=function(){this.data.sort([{column:this.admCol},{column:this.nameCol}])};
cp.charts.DataContainer.prototype.sortByPop=function(a){this.data.sort([{column:this.getPopColumnIndex(a),desc:!0},{column:this.nameCol}])};cp.charts.DataContainer.prototype.sortByValue=function(a){this.sortByPop(a)};cp.charts.DataContainer.prototype.sortByID=function(a){this.data.sort([{column:this.idCol(a)}])};
cp.charts.ChartDialog=function(a,b,d,h,g,k,e,f){this.data=a;this.dataType=b;var c=cp.getVizValue(60,50),j=cp.getVizValue(cp.getLangText("Alle","Select All"),"X"),l=cp.getVizValue(cp.getLangText("Alle abw\u00e4hlen","Unselect All"),"O"),p=void 0==d||d==cp.charts.ChartDialog.SORT_NAME?"selected":"";d=d==cp.charts.ChartDialog.SORT_POP?"selected":"";c='<div id="cp_chart_logo_'+b+'"  class="ui-corner-all ui-widget ui-widget-content""><img src="/images/logo60.png" width="'+c+'" height="'+c+'" alt="Logo" title="City Population"></div>'+
('<div id="cp_chart_adv_div_'+b+'">');c+='<iframe id="cp_chart_adv_'+b+'" scrolling="no"></iframe>';c+="</div>";c+='<div id="cp_chart_date_div_'+b+'" class="ui-corner-all">';c+="<div><label>"+cp.getLangText("Bezug","Reference")+"</label></div>";c+='<select id="cp_chart_date_select_'+b+'" size="3" '+(!0!=e?"multiple":"")+' class="ui-corner-all ui-widget ui-widget-content">';void 0==f&&(f=a.getNumberOfPopColumns()-1);for(var m=0;m<a.getNumberOfPopColumns();m++)var q=a.getPopColumnIndex(m),c=c+('<option id="cp_chart_date_opt_'+
b+"_"+m+'" value="'+m+'"'+(m==f?" selected":"")+">"+a.getColumnLabel(q)+"</option>");c+="</select>";!0!=e&&1<a.getNumberOfPopColumns()&&(c+='<div><button id="cp_chart_selalldates_but_'+b+'">'+j+'</button> <button id="cp_chart_unselalldates_but_'+b+'">'+l+"</button></div>");c+="</div>";c+='<div id="cp_chart_sort_div_'+b+'" class="ui-corner-all">';c+="<div><label>"+cp.getLangText("Sortierung","Sorting")+"</label></div>";c+='<select id="cp_chart_sort_select_'+b+'" size="1"  class="ui-corner-all ui-widget ui-widget-content">';
c+='<option id="cp_chart_sort_opt_'+b+'_0" value="0" '+p+">Name</option>";c+='<option id="cp_chart_sort_opt_'+b+'_1" value="1" '+d+">"+(void 0==k?cp.getLangText("Einwohnerzahl","Population"):k)+"</option>";0<=a.getAdmColumnIndex()&&(c+='<option id="cp_chart_sort_opt_'+b+'_2" value="2">'+(void 0==g?cp.getVizValue(cp.getLangText("Verwaltungsgebiet","Administrative Area"),cp.getLangText("Verw.gebiet","Adm. Area")):g)+"</option>");c+="</select></div>";c+='<div id="cp_chart_place_div_'+b+'" class="ui-corner-all">';
c+="<div><label>"+(void 0==g?b==cp.charts.ChartDialog.CITY_DATA?cp.getLangText("Orte","Places"):cp.getLangText("Verwaltungsgebiete","Administrative Areas"):g)+"</label></div>";c+='<div><button id="cp_chart_selallplaces_but_'+b+'">'+j+'</button> <button id="cp_chart_unselallplaces_but_'+b+'">'+l+"</button></div>";c+='<select id="cp_chart_place_select_'+b+'" multiple class="ui-corner-all ui-widget ui-widget-content">';for(m=0;m<a.getNumberOfRows();m++)c+='<option id="cp_chart_place_opt_'+b+"_"+a.getID(m)+
'" value="'+a.getID(m)+'">'+a.getName(m)+"</option>";c+="</select></div>";c+='<div id="cp_chart_tabs_'+b+'" ><ul>';c+='<li><a href="#cp_chart_tab_'+b+'-1">'+cp.getLangText("Gr\u00f6sse","Size")+"</a></li>";c+='<li><a href="#cp_chart_tab_'+b+'-2">'+cp.getLangText("Anteil","Portion")+"</a></li>";g=2;1<a.getNumberOfPopColumns()&&!0!=e&&(c+='<li><a href="#cp_chart_tab_'+b+'-3">'+cp.getLangText("Ver\u00e4nderung","Change")+"</a></li>",c+='<li><a href="#cp_chart_tab_'+b+'-4">'+cp.getLangText("Entwicklung",
"Development")+"</a></li>",g=4);c+="</ul>";for(m=1;m<=g;m++)c+='<div id="cp_chart_tab_'+b+"-"+m+'" style="overflow-x:scroll; overflow-y:hidden"></div>';c+="</div>";a=document.createElement("div");a.id="cp_chart_dialog_div_"+b;a.className="ui-corner-all ui-widget ui-widget-content";a.innerHTML=c;document.getElementsByTagName("body")[0].appendChild(a);this.activeTab=0;var n=this;$("#cp_chart_tabs_"+b).tabs({activate:function(){n.activeTab=$(this).tabs("option","active");n.draw()}});$("#cp_chart_selalldates_but_"+
b).button().click(function(){n.selectAllIn(cp.charts.ChartDialog.DATE_SELECT);n.draw()});$("#cp_chart_unselalldates_but_"+b).button().click(function(){n.unselectAllIn(cp.charts.ChartDialog.DATE_SELECT);n.draw()});$("#cp_chart_selallplaces_but_"+b).button().click(function(){n.selectAllIn(cp.charts.ChartDialog.PLACE_SELECT);n.draw()});$("#cp_chart_unselallplaces_but_"+b).button().click(function(){n.unselectAllIn(cp.charts.ChartDialog.PLACE_SELECT);n.draw()});$(a).dialog({width:cp.getVizValue(750,320),
minWidth:cp.getVizValue(538,320),height:cp.getVizValue(500,460),minHeight:cp.getVizValue(470,460),resizable:!0,title:void 0==h?cp.getLangText("Bev\u00f6lkerungsdiagramm","Population Charts"):h,autoOpen:!1,resizeStop:function(){n.resizeTab()}});$("#cp_chart_logo_"+b).click(function(){n.close()});$("#cp_chart_date_select_"+b).change(function(){n.sort()});$("#cp_chart_sort_select_"+b).change(function(){n.sort()});$("#cp_chart_place_select_"+b).change(function(){n.draw()})};
cp.charts.ChartDialog.CITY_DATA=1;cp.charts.ChartDialog.ADM_DATA=2;cp.charts.ChartDialog.prototype.getData=function(){return this.data};cp.charts.ChartDialog.DATE_SELECT="date";cp.charts.ChartDialog.REF_SELECT="date";cp.charts.ChartDialog.SORT_SELECT="sort";cp.charts.ChartDialog.PLACE_SELECT="place";cp.charts.ChartDialog.prototype.selectAllIn=function(a){$("#cp_chart_"+a+"_select_"+this.dataType+" option").prop("selected",!0)};
cp.charts.ChartDialog.prototype.unselectAllIn=function(a){$("#cp_chart_"+a+"_select_"+this.dataType+" option").prop("selected",!1)};cp.charts.ChartDialog.prototype.getSelectedIn=function(a,b){var d=[];$("#cp_chart_"+a+"_select_"+this.dataType+" option").each(function(){$(this).prop("selected")&&(!1==b?d.push($(this).attr("value")):d.push(parseInt($(this).attr("value"))))});return d};
cp.charts.ChartDialog.prototype.setSelectedIn=function(a,b,d){$("#cp_chart_"+a+"_opt_"+this.dataType+"_"+b).prop("selected",d)};cp.charts.ChartDialog.SIZE_CHART=1;cp.charts.ChartDialog.PORTION_CHART=2;cp.charts.ChartDialog.CHANGE_CHART=3;cp.charts.ChartDialog.DEVELOPMENT_CHART=4;cp.charts.ChartDialog.ALL_PLACES="all";cp.charts.ChartDialog.ONE_PLACE="one";cp.charts.ChartDialog.ADD_PLACE="add";cp.charts.ChartDialog.SORT_NAME=0;cp.charts.ChartDialog.SORT_POP=1;cp.charts.ChartDialog.SORT_ADM=2;
cp.charts.ChartDialog.prototype.resizeTab=function(){var a=$("#cp_chart_tabs_"+this.dataType).height(),b=$("#cp_chart_tab_"+this.dataType+"-"+(this.activeTab+1)).position().top;$("#cp_chart_tab_"+this.dataType+"-"+(this.activeTab+1)).height(a-b)};
cp.charts.ChartDialog.prototype.sort=function(){var a=this.getSelectedIn(cp.charts.ChartDialog.SORT_SELECT,!0);if(a==cp.charts.ChartDialog.SORT_NAME)this.data.sortByName();else if(a==cp.charts.ChartDialog.SORT_POP){a=this.getSelectedIn(cp.charts.ChartDialog.DATE_SELECT,!0);if(0==a.length){this.setSelectedIn(cp.charts.ChartDialog.SORT_SELECT,cp.charts.ChartDialog.SORT_NAME,!0);return}this.data.sortByPop(a[a.length-1])}else this.data.sortByAdmin();this.draw()};
cp.charts.ChartDialog.prototype.showMessage=function(a,b){$("#cp_chart_tab_"+this.dataType+"-"+(this.activeTab+1)).html('<p style="font-family:Arial; font-size:13px">'+cp.getLangText(a,b)+"</p>")};
cp.charts.ChartDialog.prototype.draw=function(a,b,d){void 0!=b&&(b==cp.charts.ChartDialog.ALL_PLACES?this.selectAllIn(cp.charts.ChartDialog.PLACE_SELECT):(b!=cp.charts.ChartDialog.ADD_PLACE&&this.unselectAllIn(cp.charts.ChartDialog.PLACE_SELECT),this.setSelectedIn(cp.charts.ChartDialog.PLACE_SELECT,d,!0)));void 0!=a&&$("#cp_chart_tabs_"+this.dataType).tabs("option","active",a-1);var h=this.getSelectedIn(cp.charts.ChartDialog.DATE_SELECT,!0);if(0==h.length)this.showMessage("Kein Bezug ist ausgew\u00e4hlt!",
"No reference is selected!");else if(1<h.length&&this.activeTab+1==cp.charts.ChartDialog.PORTION_CHART)this.showMessage("Nur ein Bezugdatum ausw\u00e4hlen!","Select only one reference date!");else if(1==h.length&&this.activeTab+1>cp.charts.ChartDialog.PORTION_CHART)this.showMessage("Mehrere Bezugdaten ausw\u00e4hlen!","Select more than one reference date!");else{var g=this.getSelectedIn(cp.charts.ChartDialog.PLACE_SELECT,!1);if(0==g.length)this.showMessage("Kein Ort ist ausgew\u00e4hlt!","No place is selected!");
else{a=[];for(b=0;b<this.data.getNumberOfRows();b++){d=this.data.getID(b);for(var k=0;k<g.length;k++)g[k]==d&&a.push(b)}k=new google.visualization.DataView(this.data.getData());d=[this.data.nameCol];for(b=0;b<h.length;b++)d.push(this.data.getPopColumnIndex(h[b]));k.setColumns(d);k.setRows(a);if(this.activeTab+1==cp.charts.ChartDialog.SIZE_CHART)a=200+15*g.length*h.length,a={width:a,height:1E3,colors:cp.charts.colors,fontSize:11,bar:{groupWidth:"75%"},chartArea:{top:20,height:180,left:80,width:a-200},
vAxis:{minValue:0},hAxis:{textStyle:{fontSize:11},slantedText:!0,slantedTextAngle:90,maxTextLines:1}},b=new google.visualization.ColumnChart(document.getElementById("cp_chart_tab_"+this.dataType+"-"+(this.activeTab+1))),b.draw(k,a);else if(this.activeTab+1==cp.charts.ChartDialog.PORTION_CHART){for(var e=!0,f=0;f<h.length;f++){for(b=0;b<a.length;b++){var c=this.data.getValue(a[b],d[f+1]);if(0>c){e=!1;break}}if(!e)break}!e||this.data.getColumnProperty(d[1],cp.charts.COLTYPE_PROP)==cp.charts.DIVVAL_COL?
this.showMessage("Anzeige nicht sinnvoll!","Visualization not reasonable!"):(a=550,a={width:a,height:1E3,colors:cp.charts.colors,fontSize:11,sliceVisibilityThreshold:0.02,pieResidueSliceLabel:cp.getLangText("Andere","Others"),is3D:!0,chartArea:{top:20,height:290,left:20,width:a-20}},b=new google.visualization.PieChart(document.getElementById("cp_chart_tab_"+this.dataType+"-"+(this.activeTab+1))),b.draw(k,a))}else if(this.activeTab+1==cp.charts.ChartDialog.CHANGE_CHART){k=new google.visualization.DataView(k);
f=[0];for(b=1;b<h.length;b++){var e=this.data.getColumnProperty(d[b],cp.charts.COLDATE_PROP),j=this.data.getColumnProperty(d[b+1],cp.charts.COLDATE_PROP);eval("cp.charts.ChartDialog.change"+b+(b+1)+" = function (data, rowNum) {var v1 = data.getValue(rowNum,"+b+");var v2 = data.getValue(rowNum,"+(b+1)+");return ((v1>0) && (v2>0)) ? cp.data.computeAnnualChange('"+e.toISOString().substr(0,10)+"','"+j.toISOString().substr(0,10)+"',v1,v2) : null }");e={calc:eval("cp.charts.ChartDialog.change"+b+(b+1)),
type:"number",label:e.getFullYear()+" \u2192 "+j.getFullYear()+cp.getLangText(" (in % pro Jahr) "," (in % per year)")};f.push(e)}k.setColumns(f);k.setRows(0,a.length-1);e=j=!0;for(f=1;f<h.length;f++){for(b=0;b<a.length;b++){var c=this.data.getValue(a[b],d[f]),l=this.data.getValue(a[b],d[f+1]);0<c&&l>c&&(j=!1);0<l&&l<c&&(e=!1);if(!j&&!e)break}if(!j&&!e)break}a=200+15*g.length*(h.length-1);a={width:a,height:1E3,colors:cp.charts.colors,fontSize:11,bar:{groupWidth:"75%"},chartArea:{top:20,height:180,
left:80,width:a-200},vAxis:{},hAxis:{textStyle:{fontSize:11},slantedText:!0,slantedTextAngle:90,maxTextLines:1}};e?a.vAxis.minValue=0:j&&(a.vAxis.maxValue=0);b=new google.visualization.ColumnChart(document.getElementById("cp_chart_tab_"+this.dataType+"-"+(this.activeTab+1)));b.draw(k,a)}else if(this.activeTab+1==cp.charts.ChartDialog.DEVELOPMENT_CHART){h=new google.visualization.DataTable;h.addColumn({type:"date",label:cp.getLangText("Datum","Date"),pattern:"yyyy-MM-dd"});g=this.getSelectedIn(cp.charts.ChartDialog.SORT_SELECT,
!0);for(b=0;b<a.length&&!(h.addColumn("number",this.data.getName(a[b])),13==b&&g==cp.charts.ChartDialog.SORT_POP);b++);e=k=null;for(f=1;f<d.length;f++){r=[this.data.getColumnProperty(d[f],cp.charts.COLDATE_PROP)];1==f?k=new Date(r):f==d.length-1&&(e=new Date(r));for(b=0;b<a.length&&!(j=this.data.getValue(a[b],d[f]),0<j?r.push(j):r.push(null),0<j&&(mapPop=j),13==b&&g==cp.charts.ChartDialog.SORT_POP);b++);h.addRow(r)}a=cp.data.dateDiffInYears(k,e);a=Math.max(280,12*a);a={width:a+80+200,height:1E3,colors:cp.charts.colors,
fontSize:11,chartArea:{top:20,height:260,left:80,width:a},vAxis:{minValue:0},pointSize:4};b=new google.visualization.LineChart(document.getElementById("cp_chart_tab_"+this.dataType+"-"+(this.activeTab+1)));b.draw(h,a)}}}$("#cp_chart_tabs_"+this.dataType).tabs("refresh");this.resizeTab()};
cp.charts.ChartDialog.prototype.open=function(){$("#cp_chart_adv_"+this.dataType).attr("src",location.protocol+"//"+location.host+"/diagradv.html");$("#cp_chart_dialog_div_"+this.dataType).dialog("open");$("#cp_chart_date_select_"+this.dataType).blur()};cp.charts.ChartDialog.prototype.close=function(){$("#cp_chart_dialog_div_"+this.dataType).dialog("close")};
